CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'Medium',
  status TEXT NOT NULL DEFAULT 'Pending',
  due_label TEXT NOT NULL DEFAULT 'Today',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
